name: CI/CD Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  APP_HOME: /var/www/profixmed
  SERVICE: profixmedweb.service

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm install

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore & Build
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore

      - name: Publish project
        run: |
          dotnet publish ./ProfixmedWeb.csproj --configuration Release --no-restore -o ./publish

      - name: Install SSH key & known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy, link shared, switch release, restart
        run: |
          set -e
          TIMESTAMP=$(date -u +%Y%m%d_%H%M%S)
          RELEASE_DIR=$APP_HOME/releases/$TIMESTAMP

          ssh -i ~/.ssh/id_rsa root@${{ secrets.SSH_HOST }} "mkdir -p $RELEASE_DIR"

          rsync -avz --delete \
            -e "ssh -i ~/.ssh/id_rsa" \
            ./publish/ \
            root@${{ secrets.SSH_HOST }}:$RELEASE_DIR/

          ssh -i ~/.ssh/id_rsa root@${{ secrets.SSH_HOST }} "\
            mkdir -p $APP_HOME/shared $APP_HOME/shared/Files $APP_HOME/releases && \
            ln -sfn $APP_HOME/shared/Files                       $RELEASE_DIR/wwwroot/Files && \
            if [ -f $APP_HOME/shared/appsettings.Production.json ]; then ln -sfn $APP_HOME/shared/appsettings.Production.json $RELEASE_DIR/appsettings.Production.json; fi && \
            ln -sfn $RELEASE_DIR $APP_HOME/current && \
            systemctl restart $SERVICE \
          "

      - name: Remove SSH key
        run: rm -f ~/.ssh/id_rsa
